// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package main

import (
	"github.com/google/wire"
	"github.com/scalent.io/scalent-hrms/internal/auth"
	"github.com/scalent.io/scalent-hrms/internal/middleware"
	"github.com/scalent.io/scalent-hrms/pkg/casbin"
	"github.com/scalent.io/scalent-hrms/pkg/db/cache"
	"github.com/scalent.io/scalent-hrms/pkg/db/sqlx"
	"github.com/scalent.io/scalent-hrms/pkg/reacher"
	"github.com/scalent.io/scalent-hrms/services/core/repo"
	"github.com/scalent.io/scalent-hrms/services/core/service"
	"github.com/scalent.io/scalent-hrms/services/core/web"
)

// Injectors from wire.go:

func initServer(config2 *CoreConfig) (*web.CoreHandlerRegistry, error) {
	serverConfig := config2.Server
	cacheConfig := NewCacheConfig()
	client, err := cache.NewRedisInstance(cacheConfig)
	if err != nil {
		return nil, err
	}
	dbConfig := config2.DB
	db, err := sqlx.NewDBConn(dbConfig)
	if err != nil {
		return nil, err
	}
	enforcer := casbin.InitCasbin(db)
	authImpl, err := auth.NewAuthImpl(client, db, enforcer)
	if err != nil {
		return nil, err
	}
	middlewareImpl, err := middleware.NewMiddlewareImpl(authImpl)
	if err != nil {
		return nil, err
	}
	homeServiceImpl, err := service.NewHomeServiceImpl()
	if err != nil {
		return nil, err
	}
	userRepoImpl, err := repo.NewUserRepoImpl(db)
	if err != nil {
		return nil, err
	}
	serviceConfig := NewServiceConfig()
	userServiceImpl, err := service.NewUserServiceImpl(userRepoImpl, serviceConfig)
	if err != nil {
		return nil, err
	}
	loginRepoImpl, err := repo.NewLoginRepoImpl(db)
	if err != nil {
		return nil, err
	}
	loginServiceImpl, err := service.NewLoginServiceImpl(loginRepoImpl, authImpl, userRepoImpl)
	if err != nil {
		return nil, err
	}
	employeeRepoImpl, err := repo.NewEmployeeRepoImpl(db)
	if err != nil {
		return nil, err
	}
	employeeServiceImpl, err := service.NewEmployeeServiceImpl(employeeRepoImpl)
	if err != nil {
		return nil, err
	}
	attendanceLogRepoImpl, err := repo.NewAttendanceLogRepoImpl(db)
	if err != nil {
		return nil, err
	}
	attendanceLogServiceImpl, err := service.NewAttendanceLogServiceImpl(attendanceLogRepoImpl)
	if err != nil {
		return nil, err
	}
	coreHandlerRegistryOptions := web.CoreHandlerRegistryOptions{
		Config:               serverConfig,
		Middleware:           middlewareImpl,
		HomeService:          homeServiceImpl,
		UserService:          userServiceImpl,
		LoginService:         loginServiceImpl,
		EmployeeService:      employeeServiceImpl,
		AttendanceLogService: attendanceLogServiceImpl,
	}
	coreHandlerRegistry := web.NewCoreHandlerRegistry(coreHandlerRegistryOptions)
	return coreHandlerRegistry, nil
}

// wire.go:

var CoreModuleSet = wire.NewSet(wire.FieldsOf(new(*CoreConfig), "server", "db", "Reacher"), NewCacheConfig, cache.NewRedisInstance, casbin.InitCasbin, sqlx.NewDBConn, NewServiceConfig, reacher.NewReacherClient, wire.Struct(new(web.CoreHandlerRegistryOptions), "*"), web.NewCoreHandlerRegistry, auth.NewAuthImpl, middleware.NewMiddlewareImpl, wire.Bind(new(middleware.Middleware), new(*middleware.MiddlewareImpl)), repo.NewHomeRepoImpl, wire.Bind(new(service.HomeRepo), new(*repo.HomeRepoImpl)), service.NewHomeServiceImpl, wire.Bind(new(service.HomeService), new(*service.HomeServiceImpl)), repo.NewUserRepoImpl, wire.Bind(new(service.UserRepo), new(*repo.UserRepoImpl)), service.NewUserServiceImpl, wire.Bind(new(service.UserService), new(*service.UserServiceImpl)), repo.NewLoginRepoImpl, wire.Bind(new(service.LoginRepo), new(*repo.LoginRepoImpl)), service.NewLoginServiceImpl, wire.Bind(new(service.LoginService), new(*service.LoginServiceImpl)), repo.NewEmployeeRepoImpl, wire.Bind(new(service.EmployeeRepo), new(*repo.EmployeeRepoImpl)), service.NewEmployeeServiceImpl, wire.Bind(new(service.EmployeeService), new(*service.EmployeeServiceImpl)), repo.NewAttendanceLogRepoImpl, wire.Bind(new(service.AttendanceLogRepo), new(*repo.AttendanceLogRepoImpl)), service.NewAttendanceLogServiceImpl, wire.Bind(new(service.AttendanceLogService), new(*service.AttendanceLogServiceImpl)))
